[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
galaki_winner_spot_sc = "GiRmAdyLyhhfseRxeNkbnwRCr1EMqb8nzXEJ2cbP83MU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/roster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
